# Unix Makefile for CheapGlk library

# This generates two files. One, of course, is libcheapglk.a -- the library
# itself. The other is Make.cheapglk; this is a snippet of Makefile code
# which locates the cheapglk library.
#
# When you install cheapglk, you must put libcheapglk.a in the lib directory,
# and glk.h, glkstart.h, and Make.cheapglk in the include directory.
#
# The file cgunigen.c was generated by the casemap.py script, but
# that step isn't in the Makefile -- you don't have to re-generate it.
# It's based on Unicode character data, which is not platform-dependent.

# Pick a C compiler.
CC = cc
#CC = gcc -ansi

OPTIONS = -g -Wall

CFLAGS = $(OPTIONS) $(INCLUDEDIRS) $(shell pkg-config --cflags glib-2.0)
LDFLAGS = -lc $(shell pkg-config --libs glib-2.0) -lcrypto -lssl

GLKLIB = libcheapglk.a
IRCCLIENTLIB = /usr/local/lib/libircclient.a

CHEAPGLK_OBJS =  \
  cgfref.o cggestal.o cgmisc.o cgstream.o cgstyle.o cgwindow.o cgschan.o \
  cgdate.o cgunicod.o main.o gi_dispa.o gi_blorb.o cgblorb.o iffy_config.o \
  iffy_callbacks.o iffy_state.o

CHEAPGLK_HEADERS = cheapglk.h gi_dispa.h iffy_state.h iffy_config.h \
  iffy_callbacks.h iffy.h

all: $(GLKLIB) Make.cheapglk

cgunicod.o: cgunigen.c

iffy: $(CHEAPGLK_OBJS)
	$(CC) $(CFLAGS) $(CHEAPGLK_OBJS:.o=.c) $(IRCCLIENTLIB) $(LDFLAGS) -o iffy 

$(GLKLIB): $(CHEAPGLK_OBJS)
	ar r $(GLKLIB) $(CHEAPGLK_OBJS)
	ranlib $(GLKLIB)

Make.cheapglk:
	echo LINKLIBS = $(LIBDIRS) $(LIBS) > Make.cheapglk
	echo GLKLIB = -lcheapglk >> Make.cheapglk

$(CHEAPGLK_OBJS): glk.h $(CHEAPGLK_HEADERS)

clean:
	rm -f *~ *.o $(GLKLIB) Make.cheapglk iffy
